#undef TAPPING_TERM
#define TAPPING_TERM 250

#define USB_SUSPEND_WAKEUP_DELAY 0
#define SERIAL_NUMBER "xPbGR/PB7ZM9"
#define LAYER_STATE_16BIT

#define RGB_MATRIX_STARTUP_SPD 60

#define CHORDAL_HOLD
#define PERMISSIVE_HOLD
